version: "3"
services:
  logger:
    image: chentex/random-logger:latest
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.0
    environment:
      - http.host=0.0.0.0
      - transport.host=127.0.0.1
      - cluster.name=docker-cluster
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - LOGSPOUT=ignore
    ports:
      - "9200:9200"
  kibana:
    image: docker.elastic.co/kibana/kibana:5.6.0
    environment:
      - LOGSPOUT=ignore
    ports:
      - "5601:5601"
  logstash:
    image: docker.elastic.co/logstash/logstash:5.6.0
    volumes:
      - ./pipeline/:/usr/share/logstash/pipeline/
    environment:
      - LOGSPOUT=ignore
  logspout:
    image: bekt/logspout-logstash
    restart: on-failure
    environment:
      ROUTE_URIS: logstash://logstash:5000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock